Anpassungen vom Play-Test
Flamtky/DevDungeon pull request #4
Opened 2024-04-15 16:38 UTC by Flamtky

Die Play-Tests haben wichtige Verbesserungen für das Spiel hervorgebracht:

* **Verbesserungen der Sichtbarkeit:**
  - TP-Balls sind jetzt im FogOfWar sichtbar.
  - Lebensbalken sind nun nicht mehr sichtbar, wenn der Gegner nicht sichtbar ist.

* **Anpassungen der TP-Gegner:**
  - TP-Gegner schießen jetzt aus größerer Entfernung, was dem Spieler mehr Reaktionszeit gibt, um auszuweichen.
  - TP-Gegner schießen nicht mehr sofort auf einen Helden, der gerade erst den Raum betritt.
  - TP-Gegner sind nun langsamer.

* **Tutorial und UI-Verbesserungen:**
  - Alle Anleitungen/Hinweise im Tutorial wurden überarbeitet, sind jetzt verständlicher und informativer. Die Steuerung wird dynamisch aus der Config gelesen.
  - Inventarsteuerung verbessert: Inventare lassen sich nun zusätzlich mit denselben Tasten schließen, wie sie geöffnet wurden.
  - Per Rechtsklick (RMB) können Items schnell gelootet, verstaut oder in den Kessel verschoben werden.
  - Item Hover Tooltips sind jetzt richtig formatiert und überschreiten nicht mehr den Bildschirmrand.

* **Gameplay-Anpassungen:**
  - Burning Fireball Skill visuell verändert und verteilt den Bonus-Schaden schneller, wodurch der Buff deutlicher wird.
  - Schalter in Level 3 erzeugen jetzt einen Sound, der den Spieler darauf hinweist, dass sich etwas verschoben hat.
  - Die Kiste im Boss-Level enthält nun schlechteren Loot, sodass der Spieler vorher mehr sammeln muss.
  - „No Point of Return“-Hinweis im vorletzten Level, um den Spieler zu informieren, dass er möglicherweise mehr looten sollte.
  - Unfaire Löcher in Level 3 wurden entfernt und Löcher können jetzt potenziell einen Spieler halten. Vorsicht ist geboten, da nicht jedes Loch den Helden aushalten kann (zumindest nicht lange).
  - Level 3 Reward bietet nun zusätzlich höhere Reichweite für Heldenangriffe.

* **Sonstige Änderungen:**
  - Cheats wurden deaktiviert, da der Play-Test abgeschlossen ist.

@cagix kannst du kontrollieren ob das mit den Credits jetzt so passt?

2024-04-15 17:51 UTC, cagix commented
@Flamtky was genau meinst du mit "credits"?

2024-04-15 17:54 UTC, cagix requested changes
typo

2024-04-15 17:54 UTC, cagix commented on README.md
> +    -   `floor_1.png` in [`game/assets/dungeon/fire/floor/`](`game/assets/dungeon/fire/floor/floor_1.png`) (originating from @Diana)
```suggestion
    -   Files (except Health Potion) in [`dungeon/assets/items/potion/`](dungeon/assets/items/potion/) (originating from @dkirshner)
    -   Files in [`game/assets/dungeon/*/floor`](game/assets/dungeon/) each `floor_damaged.png` (originating from @dkirshner)
    -   `floor_1.png` in [`game/assets/dungeon/fire/floor/`](`game/assets/dungeon/fire/floor/floor_1.png`) (originating from @dkirshner)
```

2024-04-15 18:01 UTC, Flamtky commented
> [...] nach dem merge müssen deine änderungen dort dann auch mit einfließen.

Jo, ich werde eh noch bestimmt paar mal das Repo updaten mit eueren master branch.

2024-04-15 18:01 UTC, merged

2024-04-15 18:05 UTC, cagix approved these changes
wow. viel holz. fleissig!

eine rückfrage noch - aber wegen mir kannst du mergen (falls und wenn du darauf gewartet hast). das kann man notfalls auch "drüben" nochmal zurückdrehen.

2024-04-15 18:24 UTC, Flamtky commented on dungeon/src/contrib/components/AIComponent.java
> +    if (!this.active) {
Persönlich würde ich sagen Ja 😅. Aber ne ich habe einfach bei mir in der IDE eingestellt, dass er `this` immer machen soll. Ich finde das verbessert die Lesbarkeit vom Code. Hier habe ich wahrscheinlich den Code verändert und "vergessen" das `this` wieder zu entfernen. Falls das mit ins Haupt-Repo soll würde ich vorher das hier wieder etwas aufräumen, da viele kleine Workarounds, kleine (unwichtige) Änderungen im Framework Code vorkommen.

2024-04-15 18:27 UTC, cagix commented on dungeon/src/contrib/components/AIComponent.java
> +    if (!this.active) {
ah :) 

ja, es wäre gut, wenn du das für den pr ins haupt-repo noch als letzte clean-up-aktion im gedächtnis halten könntest. letztlich ist mir das egal, es könnte halt nur (unnötig) für mergekonflikte sorgen.

2024-04-16 08:24 UTC, AMatutat commented
> Cheats wurden deaktiviert, da der Play-Test abgeschlossen ist.

Up Up Down Down Left Right Left Right B A